import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { writeFileSync } from 'fs';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { AppModule } from './app.module.js';
import { TimingInterceptor } from './interceptors/timing.interceptor.js';
import { MeasurementModule } from './measurement/measurement.module.js';
import { PrivateAPIInvoicesModule } from './invoice/invoices.module.js';
import { PrivateAPIOfferingModule, PublicAPIOfferingModule } from './offering/offering.module.js';
import { BillingModule } from './billing/billing.module.js';
import { MargincalcModule } from './margincalc/margincalc.module.js';
import { UsersModule } from './users/users.module.js';
import { OnboardingModule } from './onboarding/onboarding.module.js';
import { PublicAPICustomerModule } from './customer/customer.module.js';
import { ScheduleModule } from '@nestjs/schedule';
import { PrivateAPIDimensionsModule, PublicAPIDimensionsModule } from './dimensions/dimensions.module.js';
import { CostModule } from './cost/cost.module.js';
import { MeasurementConfigModule } from './measurement-config/measurement-config.module.js';
import { PrivateAPISettingsModule } from './setting/settings.module.js';
import { PrivateAPIAnalyticsModule } from './analytics/analytics.module.js';
import { PrivateInboxModule } from './inbox/inbox.module.js';
import { UsageModule } from './usage/usage.module.js';
import { PortalModule } from './portal/portal.module.js';
import { CreditModule } from './credit/credit.module.js';
import { WebhookModule } from './webhook/webhook.module.js';

async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.useGlobalPipes(new ValidationPipe({ whitelist: true }));
    const config = new DocumentBuilder()
        .setTitle('MeteringCo API')
        .setDescription(
            'Welcome to the API! MeteringCo makes it easy to bill customers based on usage. We take care of the measurement of usage, creating offerings, processing payment and analyzing cost.',
        )
        .setVersion(`1.0`)
        .addTag(
            'Authentication',
            `MeteringCo API offers one form of authentication:
        <br/>
        <b>Bearer Authentication - Client Credentials</b>
        <br>
        <br>
        To access the API first get your client ClientID and Secret my emailing founders@meteringco.example, after you have gotten your credentials, you must pass them into the Body of a POST request to the auth endpoint: https://auth.meteringco.example/oauth/token
        <br>
        <br>
        See the Node JS fetch example below for a complete request which can be made

        // This assumes you've set your AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET as process.env values
        const response = await fetch(
            'https://auth.meteringco.example/oauth/token',
            {
              method: 'POST',
              headers: { 'content-type': 'application/json' },
              body: JSON.stringify({
                client_id: process.env.AUTH0_CLIENT_ID,
                client_secret: process.env.AUTH0_CLIENT_SECRET,
                audience: 'https://example1234.execute-api.us-east-1.amazonaws.com',
                grant_type: 'client_credentials',
              }),
            },
          );


`,
        )
        .addTag(
            'Offerings',
            'An offering represents, a SKU to your business. As an example a SaaS business may have a public offering where users pay per megabyte, and they could have a different offering with a big client where they pay per Gb',
        )
        .addTag(
            'Customers',
            'Customers are the clients who are interacting with your SaaS. Importantly for MeteringCo we need to know your customers Identifier and the payment channel which to charge them through',
        )
        .addTag(
            'Dimensions',
            'Create and Manage Dimensions to be used with offerings, includes the aggregation information as well as units and dimension Price. For example if an offering has Uptime and Provisioned Capacity, there should one dimension for each',
        )
        .addTag(
            'Invoices',
            'Invoices are generated by MeteringCo and sent to your customers. You can also use the API to get a list of invoices for a customer, or a specific invoice',
        )
        .addTag(
            'Analytics',
            'MeteringCo provides a number of analytics endpoints to help you understand your business. These include: Cost, Usage, Revenue, Profit, and Margins',
        )
        .addTag('Settings', 'Manage MeteringCo platform settings')
        .addTag('Environment', 'Manage MeteringCo platform environments')
        .addServer('http://localhost:3000/', 'local')
        .addServer('https://api.qa.meteringco.example', 'qa')
        .addServer('https://api.prod.meteringco.example', 'prod')
        .addBearerAuth(
            {
                type: 'oauth2',
                scheme: 'bearer',
                bearerFormat: 'JWT',
                in: 'Header',
                description: 'Use bearer token to authenticate `Bearer <your access token>`',
                flows: {
                    clientCredentials: {
                        tokenUrl: 'https://auth.meteringco.example/oauth/token',
                        scopes: {},
                    },
                },
            },
            'bearer',
        )
        .build();
    const document = SwaggerModule.createDocument(app, config, {
        include: [
            MeasurementModule,
            PublicAPIOfferingModule,
            PrivateAPIOfferingModule,
            BillingModule,
            AppModule,
            MargincalcModule,
            UsersModule,
            OnboardingModule,
            PublicAPICustomerModule,
            ScheduleModule,
            PublicAPIDimensionsModule,
            PrivateAPIDimensionsModule,
            CostModule,
            MeasurementConfigModule,
            PrivateAPISettingsModule,
            PrivateAPIAnalyticsModule,
            PrivateInboxModule,
            UsageModule,
            PortalModule,
            PrivateAPIInvoicesModule,
            CreditModule,
            WebhookModule,
        ],
    });
    writeFileSync('./docs/open-api-private-spec.json', JSON.stringify(document, null, 2));
    // For some reason the app doesn't want to close so we need to manually call app.close, I believe there may be some service which cannot initalize underneath (likely redis and bullmq)
    await app.close();
    console.log('finished!');
}
bootstrap();
