apiVersion: apps/v1
kind: Deployment
metadata:
    name: logstash-deployment-kafka
    namespace: <fill-me-in>
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1 # <2>
            maxUnavailable: 0 # <3>
        type: RollingUpdate # <1>
    selector:
        matchLabels:
            app: logstash-deployment-kafka
    template:
        metadata:
            labels:
                app: logstash-deployment-kafka
        spec:
            volumes:
                - name: config-volume
                  configMap:
                      name: replace-me
                      items:
                          - key: logstash.yml
                            path: logstash.yml
                          - key: jaas.conf
                            path: jaas.conf
                - name: logstash-pipeline-volume
                  configMap:
                      name: replace-me
                      items:
                          - key: logstash.conf
                            path: logstash.conf
            containers:
                - name: logstash-deployment-kafka
                  image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/meteringco-logstash:measurements
                  imagePullPolicy: Always
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 9600
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                      successThreshold: 3
                  livenessProbe:
                      httpGet:
                          path: /
                          port: 9600
                      initialDelaySeconds: 300
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                      successThreshold: 1
                  volumeMounts:
                      - name: config-volume
                        mountPath: /usr/share/logstash/config
                      - name: logstash-pipeline-volume
                        mountPath: /usr/share/logstash/pipeline
                      - name: shared-volume
                        mountPath: /usr/share/secrets/
                  resources:
                      limits:
                          memory: '4Gi'
                          cpu: '2500m'
                      requests:
                          memory: '4Gi'
                          cpu: '800m'
                - name: meteringco-side-car
                  image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/meteringco-side-car:live
                  imagePullPolicy: Always
                  env:
                      - name: CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: namespace-secret
                                key: CLIENT_ID
                                optional: false
                      - name: CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: namespace-secret
                                key: CLIENT_SECRET
                                optional: false
                  resources:
                      limits:
                          memory: '1Gi'
                          cpu: '500m'
                      requests:
                          memory: '1Gi'
                          cpu: '500m'
                  volumeMounts:
                      - name: shared-volume
                        mountPath: /usr/share/secrets/
