import { AggregationMethod, Rounding } from '../client/publicClient/dimension.js';

export const input = [
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['1', '2'], aggregatedValue: '3' },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['1203897457', '29290347'], // Bytes
        aggregatedValue: '1234173952',
        usageIncrement: 1024 * 1024, // 1 MB
        rounding: Rounding.Ceiling,
    },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['-1', '-2'], aggregatedValue: '-3' },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '10',
    },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05'],
        aggregatedValue: '1',
        rounding: Rounding.Ceiling,
        usageIncrement: 1,
    },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05'],
        aggregatedValue: '24',
        rounding: Rounding.Ceiling,
        usageIncrement: 24,
    },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05'],
        aggregatedValue: '0',
        rounding: Rounding.Floor,
        usageIncrement: 24,
    },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05', '0.05'],
        aggregatedValue: '0',
        rounding: Rounding.Round,
        usageIncrement: 24,
    },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['12', '3'],
        aggregatedValue: '24',
        rounding: Rounding.Round,
        usageIncrement: 24,
    },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['1000000', '2000000'], aggregatedValue: '3000000' },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '30000000000',
    },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['1', '2'],
        aggregatedValue: '2',
        rounding: Rounding.Ceiling,
        usageIncrement: 1,
    },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['1', '2'],
        aggregatedValue: '1',
        rounding: Rounding.Floor,
        usageIncrement: 1,
    },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['1', '2'],
        aggregatedValue: '2',
        rounding: Rounding.Round,
        usageIncrement: 1,
    },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['0', '0'], aggregatedValue: '0' },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['-1', '-2'],
        aggregatedValue: '-1',
        rounding: Rounding.Ceiling,
        usageIncrement: 1,
    },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['1000000', '2000000'], aggregatedValue: '1500000' },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '15000000000',
    },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['1', '2'], aggregatedValue: '1' },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '2', '3'],
        aggregatedValue: '1',
        usageIncrement: 1,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '2', '3'],
        aggregatedValue: '0',
        usageIncrement: 2,
        rounding: Rounding.Floor,
    },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['-1', '-2'], aggregatedValue: '-2' },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '0',
        usageIncrement: 2,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
        usageIncrement: 1,
        rounding: Rounding.Round,
    },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['1000000', '2000000'], aggregatedValue: '1000000' },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '10000000000',
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['1', '2'], aggregatedValue: '2' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['1', '2', '3'],
        aggregatedValue: '3',
        usageIncrement: 3,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['1', '2', '3'],
        aggregatedValue: '3',
        usageIncrement: 3,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['1', '2'],
        aggregatedValue: '0',
        usageIncrement: 3,
        rounding: Rounding.Floor,
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['0', '0'], aggregatedValue: '0' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['0', '0'],
        aggregatedValue: '0',
        usageIncrement: 1,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['0', '0'],
        aggregatedValue: '0',
        usageIncrement: 1,
        rounding: Rounding.Round,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['0', '0'],
        aggregatedValue: '0',
        usageIncrement: 10,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['0', '9'],
        aggregatedValue: '0',
        usageIncrement: 10,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['0', '20'],
        aggregatedValue: '20',
        usageIncrement: 10,
        rounding: Rounding.Ceiling,
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['-1', '-2'], aggregatedValue: '-1' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['1000000', '2000000'], aggregatedValue: '2000000' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '20000000000',
    },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['1', '2'], aggregatedValue: '2' },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '2', '3', '4', '5'],
        aggregatedValue: '5',
        usageIncrement: 5,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1', '4'],
        aggregatedValue: '5',
        usageIncrement: 5,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1'],
        aggregatedValue: '0',
        usageIncrement: 5,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1', '1'],
        aggregatedValue: '4',
        usageIncrement: 4,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1', '1'],
        aggregatedValue: '4',
        usageIncrement: 1,
        rounding: Rounding.Floor,
    },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['1', '2'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['0', '0'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['-1', '-2'], aggregatedValue: '2' },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['-1', '-2'],
        aggregatedValue: '2',
        usageIncrement: 2,
        rounding: Rounding.Ceiling,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['-1', '-2'],
        aggregatedValue: '2',
        usageIncrement: 2,
        rounding: Rounding.Floor,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['-1', '-2'],
        aggregatedValue: '2',
        usageIncrement: 2,
        rounding: Rounding.Round,
    },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '10',
    },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['1000000', '2000000'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['10000000000', '20000000000'], aggregatedValue: '2' },
];
